import matplotlib.pyplot as plt
from matplotlib.figure import Figure
from matplotlib.axes import Axes

def set_style(obj, style: str) -> Figure:
    """
    Renders the lines and text of a Figure or Axes into a new Figure 
    using the specified matplotlib style.
    
    Parameters
    ----------
    obj : matplotlib.figure.Figure or matplotlib.axes.Axes
        The figure or axes to re-render.
    style : str
        The matplotlib stylesheet name (e.g., 'ggplot', 'seaborn-v0_8').
        
    Returns
    -------
    matplotlib.figure.Figure
        A new figure recreated with the specified style.
    """
    if isinstance(obj, Figure):
        fig = obj
    elif isinstance(obj, Axes):
        fig = obj.figure
    else:
        raise TypeError("obj must be a matplotlib Figure or Axes")
        
    with plt.style.context(style):
        # Create a new figure with the same dimensions
        new_fig = plt.figure(figsize=fig.get_size_inches(), dpi=fig.dpi)
        
        for ax in fig.axes:
            # Ensure compatible geometry
            if hasattr(ax, 'get_subplotspec'):
                ss = ax.get_subplotspec()
                rows, cols, start, stop = ss.get_geometry()
                new_ax = new_fig.add_subplot(rows, cols, (start + 1, stop + 1))
            elif hasattr(ax, 'get_geometry'):
                geometry = ax.get_geometry()
                new_ax = new_fig.add_subplot(*geometry)
            else:
                new_ax = new_fig.add_axes(ax.get_position())
            
            # Copy titles and labels
            new_ax.set_title(ax.get_title())
            new_ax.set_xlabel(ax.get_xlabel())
            new_ax.set_ylabel(ax.get_ylabel())
            
            # Copy limits
            new_ax.set_xlim(ax.get_xlim())
            new_ax.set_ylim(ax.get_ylim())
            
            # Copy lines
            for line in ax.lines:
                x = line.get_xdata()
                y = line.get_ydata()
                label = line.get_label()
                marker = line.get_marker()
                linestyle = line.get_linestyle()
                
                # Check if it was generated by a default cycle or specifically set,
                # For simplicity, we keep default styling unless label is explicit
                kwargs = {}
                if label and not label.startswith('_'):
                    kwargs['label'] = label
                    
                if marker not in ('', 'None', None):
                    kwargs['marker'] = marker
                    
                if linestyle not in ('', 'None', None):
                    kwargs['linestyle'] = linestyle
                    
                new_ax.plot(x, y, **kwargs)
                            
            # Copy legend if it exists
            if ax.get_legend():
                new_ax.legend()
                
        # Copy figure suptitle
        if fig._suptitle:
            new_fig.suptitle(fig._suptitle.get_text())
            
        new_manager = new_fig.canvas.manager
        if new_manager:
            new_manager.canvas.figure = new_fig
            new_fig.set_canvas(new_manager.canvas)
            
    return new_fig
